baseURL = 'https://dailyl.github.io/'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = "github.com/geekifan/zero-academic-page"

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Dianzhao Li"
      description = "Doctoral Candidate in [Technische Universität Dresden](https://tu-dresden.de/bu/verkehr/ivw/osv), Research Scientist in [ScaDS.AI Dresden/Leipzig](https://scads.ai/)"
      motto = "Focusing on Reinforcement Learning and Autonomous Driving."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5
    [[languages.en.menu.main]]
      name = 'Referee'
      url = '#referee'
      weight = 6
    [[languages.en.menu.main]]
      name = 'Internships'
      url = '#internships'
      weight = 7
    [[languages.en.menu.main]]
      name = 'Teaching'
      url = '#teaching'
      weight = 8
      


[params]
  profilePicture = "images/profile.png"
  enableDarkMode = true
  customCSS = ["/css/custom.css"]
  
  [[params.social]]
    name = "email"
    url = "mailto:dianzhao.li@tu-dresden.de"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "github"
    url = "https://github.com/DailyL"
    icon = "fab fa-github"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/citations?user=i65JnxwAAAAJ&hl"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "researchgate"
    url = "https://www.researchgate.net/profile/Dianzhao-Li?ev=hdr_xprf"
    icon = "fab fa-researchgate"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/dianzhao-li"
    icon = "fab fa-linkedin"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
